select count(*) from customer

copy customer to 'c:/customer.csv'csv 

select "Gender" from customer

--1.what is the total revenue generated by male vs. female
select "Gender",
	sum("Purchase Amount (USD)") as revenue
from customer
group by "Gender"

--2.which cutomers used a discount but still spent more than the average purchase amount
select "Customer ID","Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (select avg("Purchase Amount (USD)")from customer)

--3.which are the top 5 products with the highest average review rating.
select "Item Purchased",round(avg("Review Rating"::numeric),2) as "Average Product Rating"
from custome